
services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    command: >
      mongod
      --wiredTigerCacheSizeGB 1
      --wiredTigerCollectionBlockCompressor snappy
      --wiredTigerJournalCompressor snappy
      --wiredTigerEngineConfigString cache_size=1GB
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: '4G'
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  scylladb:
    image: scylladb/scylla:latest
    container_name: scylladb
    ports:
      - "9042:9042"     # CQL
      - "9160:9160"     # Thrift
      - "10000:10000"   # REST API
    command: >
      --smp 2
      --memory 2G
      --overprovisioned 1
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: '4G'
    volumes:
      - scylladb_data:/var/lib/scylla
    restart: unless-stopped

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Password$4
      MSSQL_PID: Express
    volumes:
      - mssql_data:/var/opt/mssql
    restart: unless-stopped

  elasticsearch:
    image: elasticsearch:8.19.3
    container_name: elasticsearch
    ports:
      - "9200:9200"     # REST API
      - "9300:9300"     # Transport layer
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - bootstrap.memory_lock=true
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: '4G'
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"     # HTTP interface
      - "9000:9000"     # Native TCP interface
    environment:
      CLICKHOUSE_DB: benchmark
      CLICKHOUSE_SKIP_USER_SETUP: 1
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: '12G' # Need more RAM to avoid out of memory issues on insert
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

volumes:
  mongodb_data:
  scylladb_data:
  mssql_data:
  elasticsearch_data:
  clickhouse_data:
