
services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    command: >
      mongod
      --wiredTigerCacheSizeGB 1
      --wiredTigerCollectionBlockCompressor snappy
      --wiredTigerJournalCompressor snappy
      --wiredTigerEngineConfigString cache_size=1GB
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: '4G'
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  scylladb:
    image: scylladb/scylla:latest
    container_name: scylladb
    ports:
      - "9042:9042"     # CQL
      - "9160:9160"     # Thrift
      - "10000:10000"   # REST API
    command: >
      --smp 2
      --memory 2G
      --overprovisioned 1
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: '4G'
    volumes:
      - scylladb_data:/var/lib/scylla
    restart: unless-stopped

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Password$4
      MSSQL_PID: Express
    volumes:
      - mssql_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  mongodb_data:
  scylladb_data:
  mssql_data:
